### ISSUE TITLE
Damn it doesn't work :(

### ISSUE THREAD

**Issue by agrublev** [viewstools/docs#23]
Such a damn shame, I was REALLY excited to try it out!

![image](https://user-images.githubusercontent.com/801433/48307146-b5092600-e4fb-11e8-95bc-ba07b2a786c2.png)

And even when it does load, I can't do anything. Can't open or create anything. Or even drag the window..

![2018-11-10 15-18-09 2018-11-10 15_18_57](https://user-images.githubusercontent.com/801433/48307163-f699d100-e4fb-11e8-9c89-fed40b88ad6b.gif)

**Comment by agrublev** [comment]
Noticed its running on a local server and found this
![image](https://user-images.githubusercontent.com/801433/48307190-9c4d4000-e4fc-11e8-9756-a78b5f784364.png)

**Comment by dariocravero** [comment]
Hey @agrublev sorry to hear that! Want to email me to dario@views.tools and we can schedule a call to work it out if that's alright? Thanks for your patience and for reaching out 🙏!

**Comment by dariocravero** [comment]
Happy to say this is fixed in the latest version of Tools that's available for download at views.tools :)
