### ISSUE TITLE
Desktop App starts up, shows created "views"then shows loading icon and never stops loading 

### ISSUE THREAD

**Issue by profhall** [viewstools/docs#24]
<img width="1427" alt="screen shot 2019-02-13 at 2 22 45 pm" src="https://user-images.githubusercontent.com/24921330/52737673-ebdb5600-2f9a-11e9-8226-2ffcef8cada6.png">

**Comment by dariocravero** [comment]
Hey @profhall! Sorry to hear Views isn't loading for you. Let's fix that! Could you try pressing `CMD+r` to reload the app? I imagine that restarting it gives you the same issue, right? Could you send me what `~/Library/Logs/viewstools/log.log` has? Btw, it might be easier to debug it through Slack, you can join https://slack.views.tools, I'm `@dario` there. Thanks!

**Comment by profhall** [comment]
Hey @dariocravero idk, what the problem was but the next day everything was working correctly. Thanks for getting back to my issue. The tool is great!

**Comment by dariocravero** [comment]
Glad to hear that @profhall! If you're liking it, wait till you see the next version with flows ;)

**Comment by profhall** [comment]
Ah man I can't wait!!
