### ISSUE TITLE
Artboard Area Scrollable 

### ISSUE THREAD

**Issue by profhall** [viewstools/docs#25]
Is there any plans to make the artboard scrollable? I am planning on teaching my ux students this tool in the very near future, it's amazing!

Please add XY scroll to the artboard area, it's difficult to edit any of the resolutions outside of mobile phones unless you're on a big screen.

**Comment by tombrewsviews** [comment]
We are glad to hear you have a good experience with Tools. 

The artboards are "pannable", meaning, you can hold the space bar, click and drag to move the artoboard around. You can also zoom in and out. Here's a little showcase. 

We will add the grabbing cursor when pressing space bar to indicate the interaction. That could make it more intuitive in the future.

![panningZooming](https://user-images.githubusercontent.com/3190986/54741229-1c2b9b00-4bbe-11e9-81be-b3cc4e1730fe.gif)

Does this answer your question?

**Comment by profhall** [comment]
Wow, I didn't know that!

Yes & Thank you...

I'm an instructor, and I plan to teach some of my colleagues that are UXDs this tool.

**Comment by dariocravero** [comment]
Amazing @profhall! Closing the issue for now :)
