### ISSUE TITLE
Indicate which files are automatically generated

### ISSUE THREAD

**Issue by dariocravero** [viewstools/docs#27]
Things we could/should do:
- made it more clear on the docs,
- put a comment at the top of any autogenerated file

cc @albertoescala

**Comment by albertoescala** [comment]
Great! I'll do. 👍

**Comment by dariocravero** [comment]
Done in https://github.com/viewstools/morph/commit/413579e66d3f839ba61c1dd06d84165fa7e4031d. Thanks @albertoescala :D
