### ISSUE TITLE
Review syntax for basic blocks

### ISSUE THREAD

**Issue by amymc** [viewstools/docs#6]
More of a discussion than an issue. 

I think the separation syntax for blocks is a bit confusing. Currently, we don't put a blank line after the most basic blocks but a blank line is required after custom blocks. While I understand the reasoning, that a blank line isn't required after basic blocks because they can't contain blocks inside,  I think it would be more consistent to require a blank line after all block types.

So for example this

```
Dashboard Vertical
when props.isLoggedIn
marginTop 0
width 100%
flex 1
flexDirection column
justifyContent space-between
Header

Intro Text
text `Welcome ${props.username}`
fontFamily Roboto
fontWeight 400
fontSize 20
textAlign center
marginTop 20
marginBottom 20
Button
isLoggedIn true
```

would become this instead
```
Dashboard Vertical
when props.isLoggedIn
marginTop 0
width 100%
flex 1
flexDirection column
justifyContent space-between
Header

Intro Text
text `Welcome ${props.username}`
fontFamily Roboto
fontWeight 400
fontSize 20
textAlign center
marginTop 20
marginBottom 20

Button
isLoggedIn true
```

Thoughts?

**Comment by dariocravero** [comment]
Yeah, I think it makes sense @amymc. Thanks for bringing it up. We discussed it with @tomatuxtemple and would be happy to take it in if someone makes a PR for it. Happy to provide some guidance over what it would take to do so in the parser if you're into it! :)

**Comment by dariocravero** [comment]
Thanks @amymc for making this happen :D! I've just updated the examples on the docs to match it cc @tomatuxtemple in case I missed any https://github.com/viewstools/docs/commit/d3955a8a56889ef9d30761d8f562a3ebbe50b35c
